config/routes.rb
MzScratch::Application.routes.draw do
  require 'cookie_detection'
  require 'subdomain'
  
  match '/cookies_test', :to => 'application#cookie_test'
  
  resources :admins
  resources :prizes
  resources :sessions, :only => [:new, :create, :destroy]
  
  constraints(Subdomain) do
    match '/' => 'admins#generate'
  end
  
  root :to => 'admins#marketing'

  match '/dashboard', :to => 'admins#dashboard'
  match '/signup',    :to => 'admins#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'

end

app/views/admins/_form.html.erb
<%= form_for @admin, :html => {:multipart => true} do |f| %>
	<div class="field">
    <%= f.label :subdomain, "Campaign Name (Subdomain)" %><br />
    <%= f.text_field :subdomain %>
  </div>
	<div class="field">
    <%= f.label :logo, "Scratchoff Cover Logo" %><br />
		<%= image_tag(@admin.logo_url) if @admin.logo? %>
    <%= f.file_field :logo %>
		<%= f.hidden_field :logo_cache %>
  </div>
	<div class="field">
    <%= f.label :pagetitle, "Page Title" %><br />
    <%= f.text_field :pagetitle %>
  </div>
	<div class="field">
    <%= f.label :background, "Background Image" %><br />
		<%= image_tag(@admin.background_url) if @admin.background? %>
    <%= f.file_field :background %>
		<%= f.hidden_field :background_cache %>
  </div>
	<div class="field">
    <%= f.label :bgcolor, "Background Color" %><br />
    <%= f.text_field :bgcolor %>
  </div>
	<div class="field">
    <%= f.label :fontcolor, "Font Color" %><br />
    <%= f.text_field :fontcolor %>
  </div>
	<div class="field">
    <%= f.label :linkcolor, "Link Color" %><br />
    <%= f.text_field :linkcolor %>
  </div>
  

	<div class="field">
    <%= f.label :name, "Administrator Name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
	<div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </div>	
	

	<div class="field">
    <%= f.label :terms, "Terms and Conditions" %><br />
    <%= f.text_area :terms %>
  </div>
	<div class="field">
    <%= f.label :losemessage, "Losing Message" %><br />
    <%= f.text_area :losemessage %>
  </div>
	<div class="field">
    <%= f.label :thankyou, "Thank You Message" %><br />
    <%= f.text_area :thankyou %>
  </div>
	<div class="field">
    <%= f.label :sponsor, "Sponsor Logo" %><br />
		<%= image_tag(@admin.sponsor_url) if @admin.sponsor? %>
    <%= f.file_field :sponsor %>
		<%= f.hidden_field :sponsor_cache %>
  </div>

	<div class="field">
    <%= f.label :loser, "Losing Image" %><br />
		<%= image_tag(@admin.loser_url) if @admin.loser? %>
    <%= f.file_field :loser %>
		<%= f.hidden_field :loser_cache %>
  </div>

	<div class="field">
    <%= f.label :limit, "Required Days Between Entries" %><br />
    <%= f.number_field :limit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
	$('#admin_fontcolor, #admin_bgcolor, #admin_linkcolor').miniColors();
</script>

app/views/admins/dashboard.html.erb
<h1><%= current_admin.subdomain %></h1>
<p><%= current_admin.name %>'s Dashboard</p>

<% if current_admin.prizes.any? %>
	
<% end %>

app/views/admins/edit.html.erb
<h1>Edit Your Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/generate.html.erb
	<% if cookies[:redeemed] || cookies[:ticket] == "-1" %>
	
		<header>
			<%= raw markdown @campaign.thankyou %>
		</header>
	<% elsif cookies[:ticket].to_i >= 1 %>
	
	<% @scritchoff = Prize.find(cookies[:ticket]) %>
		
	<header>

		<%= raw markdown @campaign.terms %>
		
	</header>
	
	<section id="scratchoff">
		<%= image_tag @campaign.logo_url.to_s, :title => @campaign.subdomain, :id => "latex" %>
		<% if @scritchoff.winmessage.include? "Sorry" %>
		<%= image_tag @campaign.loser_url.to_s, :title => "Sorry", :id => "prize" %>
		<% else %>
		<%= image_tag @scritchoff.image_url.to_s, :title => @scritchoff.name, :id => "prize" %>
		<% end %>
	</section>
	
	<section id="redemption">
		<p><%= raw @scritchoff.winmessage %></p>
		<% if @scritchoff.winmessage.include? "Sorry" %>
		<% else %>
		<p><a data-toggle="modal" data-target="#redeem_pane" class="win"> Redeem Now! </a></p>
		<% end %>
	</section>
	
	<div id="redeem_pane" class="modal hide fade in">
		<p><%= raw @scritchoff.redeemmessage %></p>
		<p class="warning">DO NOT TAP REDEEM UNTIL YOU HAVE READ ALL THE INSTRUCTIONS!</p>
		<a class="win closemodal" data-dismiss="modal" href="#survey">Redeem</a>
		
		<p>Brought to you by:</p>
		<%= image_tag @campaign.sponsor_url.to_s, :title => @campaign.subdomain, :class => "redeem_img" %>
	</div>
	
	<script type="text/javascript" charset="utf-8">
		$('#redeem_pane').modal({
			backdrop: true,
		  keyboard: true,
			show: false
		})
		$('a.closemodal').click(function() {
		   var z = confirm('<%= @scritchoff.suremessage %>')
			 if (z == true)
				 {
					alert("Thank you for participating!")
					$.cookie('redeemed', 'true', { expires: <%= @scritchoff.expiry %> });
					$.cookie('ticket', null);
					$('a.win').remove();
					$('#redemption p:first').replaceWith('<p>Thank you for participating!</p>');
				 }
			 else
				 {
					alert("You can leave this page loaded and confirm later")
				 }
		});
	</script>

	<script type = 'text/javascript'>

		function showRedeemButton() {
			$('#redemption').delay(800).animate({opacity: 1}, 1200, function(){});
		}

		function init(event) {
			$("#latex").eraser({
			    completeRatio: .5,
			    completeFunction: showRedeemButton
			});
		}
		
		addEventListener( "load", init, false );

		function remove(event) {
			$("#latex").eraser('clear');
			event.preventDefault();
		}

		function reset(event) {
			$("#latex").eraser('reset');
			event.preventDefault();
		}

	</script>

  <script>
    var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
  </script>
		
	<% else %>
	
	<% cookies[:ticket] = { :value => @scratchoff.id, :expires => @scratchoff.expiry.days.from_now } %>
	
	<% @scratchoff.inventory -= 1 unless @scratchoff.inventory.zero? %>
	<% @scratchoff.save %>
	
	<!-- <aside id="attribution">
			<span>powered by <a href="http://mobilezen.com/scratchoff">mobilezen Scratchoff</a></span>
		</aside> -->
	
	<header>

		<%= raw markdown @campaign.terms %>
		
	</header>
	
	<section id="scratchoff">
		<%= image_tag @campaign.logo_url.to_s, :title => @campaign.subdomain, :id => "latex" %>
		<% if @scratchoff.winmessage.include? "Sorry" %>
		<%= image_tag @campaign.loser_url.to_s, :title => "Sorry", :id => "prize" %>
		<% else %>
		<%= image_tag @scratchoff.image_url.to_s, :title => @scratchoff.name, :id => "prize" %>
		<% end %>
	</section>
	
	<section id="redemption">
		<p><%= raw @scratchoff.winmessage %></p>
		<% if @scratchoff.winmessage.include? "Sorry" %>
			<% cookies[:redeemed] = { :value => "true", :expires => @scratchoff.expiry.days.from_now } %>
		<% else %>
		<p><a data-toggle="modal" data-target="#redeem_pane" class="win"> Redeem Now! </a></p>
		<% end %>
	</section>
	
	<div id="redeem_pane" class="modal hide fade in">
		<p><%= raw @scratchoff.redeemmessage %></p>
		<p class="warning">DO NOT TAP REDEEM UNTIL YOU ARE WITH A PRIZE REPRESENTATIVE!</p>
		<a class="win closemodal" data-dismiss="modal" href="#survey">Redeem</a>
		
		<p>Brought to you by:</p>
		<%= image_tag @campaign.sponsor_url.to_s, :title => @campaign.subdomain, :class => "redeem_img" %>
	</div>
	
	<script type="text/javascript" charset="utf-8">
		$('#redeem_pane').modal({
			backdrop: true,
		  keyboard: true,
			show: false
		})
		$('a.closemodal').click(function() {
		   var z = confirm('<%= @scratchoff.suremessage %>')
			 if (z == true)
				 {
					alert("Thank you for participating!")
					$.cookie('redeemed', 'true', { expires: <%= @scratchoff.expiry %> });
					$('a.win').remove();
					$('#redemption p:first').replaceWith('<p>Thank you for participating!</p>');
				 }
			 else
				 {
					alert("You can leave this page loaded and redeem later")
				 }
		});
	</script>

	<script type = 'text/javascript'>

		function showRedeemButton() {
			$('#redemption').delay(800).animate({opacity: 1}, 1200, function(){});
		}

		function init(event) {
			$("#latex").eraser({
			    completeRatio: .5,
			    completeFunction: showRedeemButton
			});
		}
		
		addEventListener( "load", init, false );

		function remove(event) {
			$("#latex").eraser('clear');
			event.preventDefault();
		}

		function reset(event) {
			$("#latex").eraser('reset');
			event.preventDefault();
		}

	</script>

  <script>
    var _gaq=[["_setAccount","UA-26223809-7"],["_trackPageview"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
  </script>

<% end %>

app/views/admins/index.html.erb
<h1>Scratchoff Campaigns</h1>


<ul>
	<% @admins.each do |admin| %>
		<a href="<%= admin_path(admin) %>">
			<li>
				<%= image_tag admin.logo_url.to_s, :title => admin.name, :class => "logo" %> <%= admin.name %>
			</li>
		</a>
	
		<% if current_admin.super? %>	
			<%= button_to "Delete", admin, :method => :delete, :confirm => "Are you sure you want to do this?", :title => "Delete #{admin.name}" %>
		<% end %>
	<% end %>
</ul>

app/views/admins/marketing.html.erb
<p>You have reached this page in error.</p>

app/views/admins/new.html.erb
<%= render 'shared/error_messages' %>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<header>
	<%= image_tag @admin.logo_url.to_s, :title => @admin.name, :class => "logo" %>
</header>

<h2><%= link_to 'Edit Campaign', edit_admin_path(params[:id]) %> | <%= link_to 'Edit Prizes', prizes_path %></h2>

<h1>Subdomain: <%= @admin.subdomain %></h1>
<p><%= @admin.name %></p>
<p><%= @admin.email %></p>